platform :ios, '12.0' # 指定 iOS 的最低支持版本

target 'Runner' do
  use_frameworks! # 允许使用 Swift 的框架
  use_modular_headers! # 允许模块化的头文件

  # 安装 Flutter 的 iOS 依赖
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end